export const PENDING_VERIFICATION = "PENDING_VERIFICATION";
export const PROCESSING_VERIFICATION = "PROCESSING_VERIFICATION";
export const COMPLETED_VERIFICATION = "COMPLETED_VERIFICATION";

export const PENDING_TRANSCRIPT = "PENDING_TRANSCRIPT";
export const PROCESSING_TRANSCRIPT = "PROCESSING_TRANSCRIPT";
export const COMPLETED_TRANSCRIPT = "COMPLETED_TRANSCRIPT";

export const GET_INSTITUTIONS = "GET_INSTITUTIONS";
export const ADD_INSTITUTIONS = "ADD_INSTITUTIONS";
export const GET_MESSAGES = "GET_MESSAGES";
export const DELETE_MESSAGES = "DELETE_MESSAGES";

export const USER_VERIFICATIONS = "USER_VERIFICATIONS";
export const GET_TRANSCRIPT = "GET_TRANSCRIPT";
export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_TRANSCRIPT = "UPDATE_TRANSCRIPT ";
